modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/matthe815/mmo-parties"

[[mods]]
modId="mmoparties"
version="${version}"
displayName="MMOParties"
#updateJSONURL=""
displayURL="https://github.com/matthe815/mmo-parties"
#logoFile="logo.png"
authors="Matthe815"
description="Allows you to party up with your friends and take the world together!"